Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 1, in <module>
    import os
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 62, in adjointSolve
    v_next = v_next + v[j]*sumTerm(u_fine, t_fine, dt_fine, i, j)
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 56, in sumTerm
    return (grad(forwardFn)(u_prev, t_prev, dt_j, params, net))[i]
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/api.py", line 659, in grad_f
    _, g = value_and_grad_f(*args, **kwargs)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/api.py", line 739, in value_and_grad_f
    _check_scalar(ans)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/api.py", line 759, in _check_scalar
    raise TypeError(msg(f"had shape: {aval.shape}"))
jax._src.traceback_util.UnfilteredStackTrace: TypeError: Gradient only defined for scalar-output functions. Output had shape: (1,).
The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.
--------------------
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/pdb.py", line 1723, in main
    pdb._runscript(mainpyfile)
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/pdb.py", line 1583, in _runscript
    self.run(statement)
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/bdb.py", line 580, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 1, in <module>
    import os
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 62, in adjointSolve
    v_next = v_next + v[j]*sumTerm(u_fine, t_fine, dt_fine, i, j)
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 56, in sumTerm
    return (grad(forwardFn)(u_prev, t_prev, dt_j, params, net))[i]
TypeError: Gradient only defined for scalar-output functions. Output had shape: (1,).
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /scratch/07169/wgl/adjoint/python/Main_no_matrix.py(56)sumTerm()
-> return (grad(forwardFn)(u_prev, t_prev, dt_j, params, net))[i]
Breakpoint 1 at /scratch/07169/wgl/adjoint/python/Main_no_matrix.py:22
Post mortem debugger finished. The /scratch/07169/wgl/adjoint/python/Main_no_matrix.py will be restarted
> /scratch/07169/wgl/adjoint/python/Main_no_matrix.py(1)<module>()
-> import os
> /scratch/07169/wgl/adjoint/python/Main_no_matrix.py(22)forwardFn()
-> return net.apply({'params': params}, u[-1], t[-1], dt)
Traced<ShapedArray(float32[1])>with<JVPTrace(level=3/0)> with
  primal = Traced<ShapedArray(float32[1])>with<BatchTrace(level=1/0)> with
    val = Array([[-0.4625013 ],
       [-0.04915434],
       [-0.42770278],
       [-0.33964705],
       [ 0.84238946],
       [ 0.70379716],
       [-0.2162571 ],
       [ 2.0146828 ],
       [-0.06331155],
       [ 0.33833328],
       [-0.13760889],
       [ 0.54313684],
       [-0.2647521 ],
       [-0.11478224],
       [-0.2436145 ],
       [ 0.7962954 ],
       [-0.14768606],
       [-0.48426497],
       [ 0.97778696],
       [-0.21786201],
       [ 0.00401229],
       [-0.24588478],
       [ 0.7729619 ],
       [-0.06064492],
       [-0.14455378],
       [ 0.7937777 ],
       [ 1.8933954 ],
       [ 1.1537265 ],
       [ 0.5062003 ],
       [ 2.0488372 ],
       [-0.40207636],
       [-0.02940044],
       [-0.1192899 ],
       [ 1.4107845 ],
       [-0.1738537 ],
       [ 1.6967818 ],
       [-0.28863442],
       [ 1.0888065 ],
       [-0.16248742],
       [-0.08276486],
       [ 0.08756477],
       [-0.04881093],
       [ 0.7264901 ],
       [ 0.89575887],
       [ 0.7577072 ],
       [ 0.15913332],
       [-0.03298214],
       [-0.34446883],
       [ 1.0430089 ],
       [-0.09188858],
       [-0.23726147],
       [-0.03507254],
       [-0.09353217],
       [ 0.13746047],
       [-0.08155102],
       [-0.64178586],
       [ 3.2549877 ],
       [ 0.41883436],
       [ 0.75754493],
       [-0.1336253 ],
       [-0.3553673 ],
       [-0.17029029],
       [ 1.0832013 ],
       [-0.19384062],
       [-0.09115267],
       [-0.27754492],
       [ 0.12168463],
       [ 0.5240261 ],
       [ 0.14648445],
       [ 1.1494442 ],
       [-0.01882072],
       [ 1.0627016 ],
       [ 0.39002746],
       [ 0.9881006 ],
       [ 1.8395284 ],
       [-0.11655191],
       [ 0.9886766 ],
       [-0.16260594],
       [-0.02222255],
       [-0.02211706],
       [ 0.21822564],
       [ 0.84500515],
       [ 0.27573013],
       [-0.04627876],
       [-0.426363  ],
       [-0.256819  ],
       [ 0.88072324],
       [-0.08141282],
       [-0.22433525],
       [-0.04138343],
       [-0.14851946],
       [ 0.8666318 ],
       [ 0.7127392 ],
       [ 0.58919275],
       [ 1.5330929 ],
       [-0.19681919],
       [-0.61364675],
       [-0.37219965],
       [ 1.8759847 ],
       [-0.03850615]], dtype=float32)
    batch_dim = 0
  tangent = Traced<ShapedArray(float32[1])>with<JaxprTrace(level=2/0)> with
    pval = (ShapedArray(float32[1]), None)
    recipe = JaxprEqnRecipe(eqn_id=<object object at 0x14fc3c168c10>, in_tracers=(Traced<ShapedArray(float32[1]):JaxprTrace(level=2/0)>,), out_tracer_refs=[<weakref at 0x14fce4139310; to 'JaxprTracer' at 0x14fce41239f0>], out_avals=[ShapedArray(float32[1])], primitive=pjit, params={'jaxpr': { lambda ; a:f32[1]. let  in (a,) }, 'in_shardings': (UnspecifiedValue,), 'out_shardings': (UnspecifiedValue,), 'resource_env': None, 'donated_invars': (False,), 'name': 'fn', 'keep_unused': False, 'inline': True}, effects=set(), source_info=SourceInfo(traceback=<jaxlib.xla_extension.Traceback object at 0x14fdc4166030>, name_stack=NameStack(stack=(Transform(name='vmap'), Transform(name='jvp'), Scope(name='ResNetBlock')))))
(1,)
Traced<ShapedArray(float32[])>with<JVPTrace(level=3/0)> with
  primal = Traced<ShapedArray(float32[])>with<BatchTrace(level=1/0)> with
    val = Array([-0.4625013 , -0.04915434, -0.42770278, -0.33964705,  0.84238946,
        0.70379716, -0.2162571 ,  2.0146828 , -0.06331155,  0.33833328,
       -0.13760889,  0.54313684, -0.2647521 , -0.11478224, -0.2436145 ,
        0.7962954 , -0.14768606, -0.48426497,  0.97778696, -0.21786201,
        0.00401229, -0.24588478,  0.7729619 , -0.06064492, -0.14455378,
        0.7937777 ,  1.8933954 ,  1.1537265 ,  0.5062003 ,  2.0488372 ,
       -0.40207636, -0.02940044, -0.1192899 ,  1.4107845 , -0.1738537 ,
        1.6967818 , -0.28863442,  1.0888065 , -0.16248742, -0.08276486,
        0.08756477, -0.04881093,  0.7264901 ,  0.89575887,  0.7577072 ,
        0.15913332, -0.03298214, -0.34446883,  1.0430089 , -0.09188858,
       -0.23726147, -0.03507254, -0.09353217,  0.13746047, -0.08155102,
       -0.64178586,  3.2549877 ,  0.41883436,  0.75754493, -0.1336253 ,
       -0.3553673 , -0.17029029,  1.0832013 , -0.19384062, -0.09115267,
       -0.27754492,  0.12168463,  0.5240261 ,  0.14648445,  1.1494442 ,
       -0.01882072,  1.0627016 ,  0.39002746,  0.9881006 ,  1.8395284 ,
       -0.11655191,  0.9886766 , -0.16260594, -0.02222255, -0.02211706,
        0.21822564,  0.84500515,  0.27573013, -0.04627876, -0.426363  ,
       -0.256819  ,  0.88072324, -0.08141282, -0.22433525, -0.04138343,
       -0.14851946,  0.8666318 ,  0.7127392 ,  0.58919275,  1.5330929 ,
       -0.19681919, -0.61364675, -0.37219965,  1.8759847 , -0.03850615],      dtype=float32)
    batch_dim = 0
  tangent = Traced<ShapedArray(float32[])>with<JaxprTrace(level=2/0)> with
    pval = (ShapedArray(float32[]), None)
    recipe = JaxprEqnRecipe(eqn_id=<object object at 0x14fc3c168bc0>, in_tracers=(Traced<ShapedArray(float32[1]):JaxprTrace(level=2/0)>,), out_tracer_refs=[<weakref at 0x14fce40ba900; to 'JaxprTracer' at 0x14fce40bac70>], out_avals=[ShapedArray(float32[])], primitive=squeeze, params={'dimensions': (0,)}, effects=set(), source_info=SourceInfo(traceback=<jaxlib.xla_extension.Traceback object at 0x14fce4065730>, name_stack=NameStack(stack=(Transform(name='jvp'),))))
()
> /scratch/07169/wgl/adjoint/python/Main_no_matrix.py(22)forwardFn()
-> return net.apply({'params': params}, u[-1], t[-1], dt)
> /scratch/07169/wgl/adjoint/python/Main_no_matrix.py(22)forwardFn()
-> return net.apply({'params': params}, u[-1], t[-1], dt)
Deleted breakpoint 1 at /scratch/07169/wgl/adjoint/python/Main_no_matrix.py:22
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 180, in <module>
    'Error': err,
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 62, in adjointSolve
    net))[i]
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 56, in sumTerm
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/api.py", line 659, in grad_f
    _, g = value_and_grad_f(*args, **kwargs)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/api.py", line 739, in value_and_grad_f
    _check_scalar(ans)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/api.py", line 759, in _check_scalar
    raise TypeError(msg(f"had shape: {aval.shape}"))
jax._src.traceback_util.UnfilteredStackTrace: TypeError: Gradient only defined for scalar-output functions. Output had shape: (1,).
The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.
--------------------
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/pdb.py", line 1723, in main
    pdb._runscript(mainpyfile)
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/pdb.py", line 1583, in _runscript
    self.run(statement)
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/bdb.py", line 580, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 180, in <module>
    'Error': err,
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 62, in adjointSolve
    net))[i]
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 56, in sumTerm
TypeError: Gradient only defined for scalar-output functions. Output had shape: (1,).
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /scratch/07169/wgl/adjoint/python/Main_no_matrix.py(56)sumTerm()
->
Breakpoint 2 at /scratch/07169/wgl/adjoint/python/Main_no_matrix.py:61
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 180, in <module>
    wandb.log({
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 62, in adjointSolve
    t_prev,
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 56, in sumTerm
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/api.py", line 659, in grad_f
    _, g = value_and_grad_f(*args, **kwargs)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/api.py", line 739, in value_and_grad_f
    _check_scalar(ans)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/api.py", line 759, in _check_scalar
    raise TypeError(msg(f"had shape: {aval.shape}"))
jax._src.traceback_util.UnfilteredStackTrace: TypeError: Gradient only defined for scalar-output functions. Output had shape: (1,).
The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.
--------------------
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/pdb.py", line 1723, in main
    pdb._runscript(mainpyfile)
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/pdb.py", line 1583, in _runscript
    self.run(statement)
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/bdb.py", line 580, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 180, in <module>
    wandb.log({
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 62, in adjointSolve
    t_prev,
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 56, in sumTerm
TypeError: Gradient only defined for scalar-output functions. Output had shape: (1,).
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/pdb.py", line 1750, in <module>
    pdb.main()
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/pdb.py", line 1742, in main
    pdb.interaction(None, t)
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/pdb.py", line 357, in interaction
    self._cmdloop()
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/pdb.py", line 322, in _cmdloop
    self.cmdloop()
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/pdb.py", line 422, in onecmd
    return cmd.Cmd.onecmd(self, line)
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/cmd.py", line 217, in onecmd
    return func(arg)
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/pdb.py", line 1036, in do_run
    raise Restart
pdb.Restart